name: dotnet package

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: '8.0.x'

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet '8.0.x'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display dotnet version
        run: dotnet --version

      - name: Dotnet test
        run: dotnet test ./dotnet-test-sharding.sln
