name: Dotnet test with basic setup

on: [workflow_dispatch]

jobs:
  test-single:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display dotnet version
        run: dotnet --version

      - name: Dotnet test
        run: dotnet test ./dotnet-test-sharding.sln -v:detailed
