name: Run tests with sharding

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix: 
        shards: ['1', '2']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display dotnet version
        run: dotnet --version

      - name: Dotnet test
        run: dotnet test ./dotnet-test-sharding.sln --filter Shard=${{ matrix.shards }} -c Release -l trx --results-directory 'artifacts/tests/output'

      - name: Set UUID
        if: ${{ success() || failure() }}
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: test-results-${{ steps.generate-uuid.outputs.uuid }}
          path: artifacts/tests/output/**
        
  publish-test-results:
    if: always()
    needs: test
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/tests/output


      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: ${{ success() || failure() }}
        with:
          files: ${{ env.TEST_RESULTS }}/**/*.trx
          large_files: true
          check_name: "Test results"
          report_individual_runs: true
          action_fail: true
          time_unit: milliseconds
          compare_to_earlier_commit: false
      
